
model_config:
  name: MultiTaskConformerCTC
  dmodel: 144
  reduction_factor: 4
  num_blocks: 16
  head_size: 32
  num_heads: 4
  kernel_size: 32
  fc_factor: 0.5
  dropout: 0.1

optimizer_config:
  learning_rate: 0.0001
  beta_1: 0.9
  beta_2: 0.98
  epsilon: 0.000001

decoder1_config:
  vocabulary: '.\configs\dict\words.txt'
  blank_at_zero: False
  beam_width: 1
decoder2_config:
  vocabulary: '.\configs\dict\phone.txt'
  blank_at_zero: False
  beam_width: 1
decoder3_config:
  vocabulary: '.\configs\dict\pinyin.txt'
  blank_at_zero: False
  beam_width: 1

map_path:
  phone: '.\configs\dict\pinyin2phone.map'